# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
n1 = np.zeros(10, dtype = int)
n1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [5]:
v1 = np.arange(10,50)
v1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [7]:
v1.shape

(40,)

5. Print the type of the previous array in question 3

In [9]:
type(v1)

numpy.ndarray

6. Print the numpy version and the configuration


In [11]:
print(np.__version__)

1.24.3


7. Print the dimension of the array in question 3


In [12]:
v1.ndim

1

8. Create a boolean array with all the True values

In [18]:
[v1 > 15]

[array([False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True])]

9. Create a two dimensional array




In [20]:
d2 = np.arange(10).reshape(2,5)
d2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [23]:
d3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
d3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [24]:
np.flip(d3)

AttributeError: 'numpy.ndarray' object has no attribute 'flip'

12. Create a null vector of size 10 but the fifth value which is 1 

In [29]:
n1 = np.zeros(10 ,dtype= int)
n1[5] = 1
n1

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [40]:
i1 = np.eye(3,dtype= int)
i1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [42]:
arr = np.array([1, 2, 3, 4, 5], dtype = float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [46]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])
arr3 = arr1 * arr2
arr3

array([[ 0,  8,  3],
       [28, 10, 72]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [65]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])
np.array_equal(arr1,arr2)

False

17. Extract all odd numbers from arr with values(0-9)

In [77]:
arr = np.arange(10)
arr1 = arr[arr % 2 != 0]
print(arr)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [81]:
arr1 = arr[arr % 2 != 0] = -1
print(arr1)
print(arr)

-1
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [101]:
arr = np.arange(10)
arr[5:9] = 12
arr
arr2 = np.arange(20, dtype=int).reshape(5,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

20. Create a 2d array with 1 on the border and 0 inside

In [136]:
arr2 = np.ones(20, dtype=int).reshape(5,4)
arr2

arr2[1:4,1:3] = 0
arr2

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [148]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [172]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [182]:
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [183]:
arr2d = np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [156]:
arr2d[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [185]:
arr2d = np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [188]:
arr2d[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [159]:
arr2d = np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [192]:
arr2d[0:2,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [197]:
arr2d = np.random.random((10,10))
arr2d

array([[0.12590563, 0.33683918, 0.6966283 , 0.13055686, 0.97950675,
        0.09439423, 0.66508065, 0.63107752, 0.57969933, 0.07051594],
       [0.87669057, 0.22395622, 0.32597118, 0.41496456, 0.72268532,
        0.50892759, 0.97542328, 0.28255225, 0.67594993, 0.52706346],
       [0.90919013, 0.75901926, 0.13050441, 0.62396939, 0.16677362,
        0.39558862, 0.0718236 , 0.23167918, 0.81096226, 0.02745664],
       [0.69225958, 0.6775566 , 0.1870057 , 0.41841991, 0.59180017,
        0.04109937, 0.32033099, 0.20047181, 0.07286336, 0.5536056 ],
       [0.65027718, 0.44189191, 0.54694791, 0.9091208 , 0.93023727,
        0.27549073, 0.22506981, 0.28694339, 0.15765148, 0.83229497],
       [0.61519601, 0.88534023, 0.05506116, 0.31475893, 0.70576149,
        0.34866789, 0.83831524, 0.61179167, 0.99787885, 0.20738831],
       [0.10163132, 0.54455477, 0.91668204, 0.30152119, 0.88404606,
        0.5373575 , 0.09842219, 0.63209802, 0.39798666, 0.39187522],
       [0.95917722, 0.48122134, 0.1327443

In [201]:
print(arr2d.min())
print(arr2d.max())

0.027456639714746878
0.997878854682484


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [204]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [211]:
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [208]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [214]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data

array([[ 0.11667744,  0.28124702, -1.21322173,  0.10490537],
       [ 0.10932431,  1.02983956, -0.85764027,  2.59899864],
       [ 0.56981882, -0.34785402, -0.32767538,  0.35992813],
       [-0.91657948,  1.17534528, -1.45799874, -0.29440259],
       [ 1.05842426, -0.09305846,  0.73732574,  0.51969767],
       [ 0.35545808,  2.38063803, -0.43893905,  0.99837576],
       [ 0.96306042, -0.07948511, -0.60787266, -0.85744171]])

In [218]:
new_val = data[names != 'Will']
new_val

array([[ 0.11667744,  0.28124702, -1.21322173,  0.10490537],
       [ 0.10932431,  1.02983956, -0.85764027,  2.59899864],
       [-0.91657948,  1.17534528, -1.45799874, -0.29440259],
       [ 0.35545808,  2.38063803, -0.43893905,  0.99837576],
       [ 0.96306042, -0.07948511, -0.60787266, -0.85744171]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [223]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
new_val = data[[names != 'Will'] and [names !='Joe'] ]
new_val

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


array([[-1.31375578,  0.70721085,  0.31958911,  0.15920051],
       [ 1.70185976, -0.80725335, -0.78088545, -0.2634795 ],
       [-0.13000634, -1.34802024,  0.10259038,  0.25843349],
       [ 0.21136458, -0.51361889, -1.06677894, -1.42778674]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [222]:
arr2d = np.arange(1,16).reshape(5,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [227]:
arr2d = np.arange(1,17).reshape(2,2,4)
arr2d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [234]:
np.swapaxes(arr2d, 2,0)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [236]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [242]:
arr = np.arange(12)
arr1 = np.arange(12)
np.max(arr)

11

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [243]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [250]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c= np.setdiff1d(a,b)
c


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [246]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [248]:
x@y

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [254]:
matrix = np.random.randn(2,5,2)
matrix

array([[[ 2.76976912,  2.14806618],
        [-0.24371793,  0.44347165],
        [-0.87391479, -0.14311408],
        [ 1.9772981 , -0.58434441],
        [ 0.65372891, -0.74237601]],

       [[ 2.66132313, -1.25981846],
        [-0.512092  ,  1.1918777 ],
        [-1.69892859, -0.68160889],
        [ 1.56230512, -0.25217822],
        [ 0.4097356 ,  2.28161757]]])